site_name: Pointslocal Gameplan
site_url: http://corporate.pointslocal.com
site_description: API Documentation for Pointslocal's GamePlan
site_author: Nathan Kozyra

pages:
- API:
  - Home: index.md
  - Games: api_games.md
  - Players: api_players.md
  - Schools: api_schools.md
  - Teams: api_teams.md
  - Sports: api_sports.md
  - Standings: api_standings.md
- Widgets:
  - Home: widget_index.md
  - Schedules and Results: widget_schedule.md
  - Standings: widget_standings.md
  - Teams: widget_teams.md